### PR TITLE
Navbar hamburger fixed

### LINKED ISSUE #87: Navbar not responding in Mobile mode
Its hamburger doesn't open up!!

### PR DESCRIPTION
**Pull request by Castella1313**
#87 Solved

Screenshot 2021-04-14 at 6 50 34 AM

### CODE REVIEW

**Comment by Castella1313** [comment]
@codewithvk Can you review my PR!

**Comment by codewithvk** [comment]
@Castella1313 Can you make an about, event etc option in the middle of mob version.
Also, button need  show in vertical not horizontal

**Comment by Castella1313** [comment]
@codewithvk Can you check it now?



Screenshot 2021-04-14 at 12 00 59 PM

**Comment by codewithvk** [comment]
> @codewithvk Can you check it now?
> 
> Screenshot 2021-04-14 at 12 00 59 PM

Hey, can you please add the GS logo also in the mid for mob version!

**Comment by Castella1313** [comment]
@codewithvk Its whole Navbar wasn't working properly. I had to make it again. I'm so sorry to say but I'm fed up of making changes in just one PR for just level 2.
I'm so sorry if it sounds rude.

**Comment by Castella1313** [comment]
@codewithvk Done :) Sorry for the above comment 

Screenshot 2021-04-14 at 6 51 40 PM

File: frontend/src/Components/Navbar/Navbar.js [hunk 1]
```diff
@@ -1,58 +0,0 @@
-import React from "react";
```
Comment (codewithvk) [inline frontend/src/Components/Navbar/Navbar.js:1]: Why are you delete the Navbar component??


You just need to add a media query for that not need to write the entire code again.

**Review by codewithvk — CHANGES_REQUESTED** [review]

File: frontend/src/Components/Navbar/Navbar.js (hunk 1 above)
Comment (Castella1313) [reply frontend/src/Components/Navbar/Navbar.js:1]: I didn't delete the file, I just renamed it, because the Navbar component the Navbar function were with same name, so it was showing error.

Comment (Castella1313) [reply frontend/src/Components/Navbar/Navbar.js:1]: That entire code was written in bootstrap for js, so its hamburger wasn't working, I just used react bootstrap.

Comment (codewithvk) [reply frontend/src/Components/Navbar/Navbar.js:1]: So you can add component like navComponent

File: frontend/src/Components/Login/Login.js [hunk 2]
```diff
@@ -0,0 +1,36 @@
+import React from "react"
```
Comment (codewithvk) [inline frontend/src/Components/Login/Login.js:1]: Please remove login component.

reason : [here](https://github.com/girlscript/Girscript-Community-Website/pull/83)

**Review by codewithvk — CHANGES_REQUESTED** [review]
As said before, please don't attach login component here. You can make changes with relevant PR

**Comment by codewithvk** [comment]
> @codewithvk Its whole Navbar wasn't working properly. I had to make it again. I'm so sorry to say but I'm fed up of making changes in just one PR for just level 2.
> I'm so sorry if it sounds rude.

I think here some of your misconceptions so let me try to clear them.
- This issue is only for responsive of navbar not for the login page
- and for the responsive navbar, 2 points is more than enough according to me.
still if you have any doubt then let me know , Hope you understand :)

**Comment by Castella1313** [comment]
@codewithvk done

File: frontend/src/Components/Navbar/Navbar.js (hunk 1 above)
Comment (codewithvk) [reply frontend/src/Components/Navbar/Navbar.js:1]: @Castella1313 Please make above change

**Comment by Castella1313** [comment]
@codewithvk Its done, can you see it now :)
